version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:4000
      - VITE_ML_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
      - ml-service

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/pocketds
      - ML_SERVICE_URL=http://ml-service:8000
    depends_on:
      - db
      - ml-service

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml-service/models:/app/models
      - ./ml-service/datasets:/app/datasets
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pocketds
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 